### ISSUE TITLE
How to abort export after calling CanvasCapture.stopRecord()

### ISSUE THREAD

**Issue by symetryn** [amandaghassaei/canvas-capture#11]
After I call ```CanvasCapture.stopRecord()``` there is no way to stop the export and the export callback always runs. Only way I can stop the process right now is by throwing an error in exportProgress. Is there any other way ?

**Comment by amandaghassaei** [comment]
no there is no way to stop the export, that would be a nice feature to add though.  I will label this as a feature request.

**Comment by symetryn** [comment]
Thank you for the response. It indeed would be a nice feature 🙆‍♂️ .

**Comment by JasonMHasperhoven** [comment]
Any update on this? Would also like to have this.

**Comment by amandaghassaei** [comment]
I don't have time to work on this right now, but feel free to submit a pull request!

At some point i want to do a big re-write of this lib to get rid of the old dependencies and make the api a bit nicer, but still likely 1 year away.

**Comment by JasonMHasperhoven** [comment]
Okay thanks for the update, appreciate the work you have done on this!

**Comment by amandaghassaei** [comment]
added to https://github.com/amandaghassaei/canvas-capture/discussions/29
going to close this for now.
