### ISSUE TITLE
OOM error on exporting to MP4

### ISSUE THREAD

**Issue by sdivakarrajesh** [amandaghassaei/canvas-capture#13]
![image](https://user-images.githubusercontent.com/30803637/179539687-df952a2e-ab49-46a3-bc86-4a670f6d252f.png)

I have around 125 images that i wish to convert to mp4 at 25fps in the browser. But the library fails saying OOM

**Comment by amandaghassaei** [comment]
how large are the images?
you might try exporting as webm (uses less memory) and then converting to mp4 separately on your computer.

see: https://github.com/amandaghassaei/canvas-capture#additional-notes

**Comment by sdivakarrajesh** [comment]
I use this method provided by this library 
```
CanvasCapture.beginVideoRecord({ format: CanvasCapture.MP4 });
```

Which i see first converts to webm and then uses ffmpeg.wasm to convert to mp4

**Comment by amandaghassaei** [comment]
yeah I think if you export as webm instead and then use another tool to convert to mp4 you might have better luck.

**Comment by amandaghassaei** [comment]
see: https://github.com/amandaghassaei/canvas-capture#converting-webm-to-other-formats
