### ISSUE TITLE
How to record again without reloading the page?

### ISSUE THREAD

**Issue by diras13** [amandaghassaei/canvas-capture#15]

**Comment by diras13** [comment]
It seems that if i click the start button again the size of images that generated gets doubled

**Comment by amandaghassaei** [comment]
Please see the demo page for an example of taking multiple recordings and images:
https://apps.amandaghassaei.com/canvas-capture/demo/

**Comment by diras13** [comment]
May i know where did you change in ccapture to do this multirecording?

**Comment by amandaghassaei** [comment]
the code is here: https://github.com/amandaghassaei/canvas-capture/blob/main/demo/src/index.ts

note: this isn't ccapture, this is a wrapper around it with a slightly different API.
