### ISSUE TITLE
Canvas-Capture doesn't have framerate/fps functionality for PNG capture

### ISSUE THREAD

**Issue by Jrnze** [amandaghassaei/canvas-capture#16]

**Comment by amandaghassaei** [comment]
I'm not sure what this means, can you clarify?

**Comment by Jrnze** [comment]
> 

I want to download still images of an animation in PNG format at 30 frames per second, CCapture,js lets me do that but my project is in React and I can't install CCapture thru npm so I used Canvas-Capture.

**Comment by amandaghassaei** [comment]
You can either `CanvasCapture.takePNGSnapshot()` inside your render loop each time you want to save a frame, or you can save a series of pngs as a zip with `CanvasCapture.beginPNGFramesRecord()`.  See the demo for more info:
https://github.com/amandaghassaei/canvas-capture/blob/main/demo/src/index.ts
https://apps.amandaghassaei.com/canvas-capture/demo/

You can control the framerate by how often you call  `CanvasCapture.takePNGSnapshot()` or `CanvasCapture.recordFrame()` in your render loop.  I believe this is the same way it works in CCapture.
