### ISSUE TITLE
Chrome does not support MP4 video recording?

### ISSUE THREAD

**Issue by lukeellison** [amandaghassaei/canvas-capture#19]
```
Uncaught Error: This browser does not support MP4 video recording, please try again in Chrome.
    at Object.beginVideoRecord (CanvasCapture.ts:305:11)
```

Perhaps Chrome doesn't support it but I find that unlikely. Maybe it's something strange about my setup, I've tried disabling all extensions as I know that can be a source of pain but the error persists.
Chrome version: Version 108.0.5359.98 (Official Build) (x86_64)

Is this only a problem on my machine? Or perhaps a recent update has broken the `browserSupportsMP4` function?

Thanks for your time

**Comment by cdaein** [comment]
Chrome should support `SharedArrayBuffer` but you still need to set the dev server headers as explained in [Caveats](https://github.com/amandaghassaei/canvas-capture#caveats).

I use Vite for development, and this is what I did to make it work:

```js
// vite.config.js (this file needs to be at the project root)

import { defineConfig } from "vite";

export default defineConfig({
  server: {
    headers: {
      "Cross-Origin-Embedder-Policy": "require-corp",
      "Cross-Origin-Opener-Policy": "same-origin",
    },
  },
});

```

**Comment by amandaghassaei** [comment]
thanks for the answer @cdaein, I've added a more descriptive error message to help resolve this issue.
closing this, as mp4 is working in Chrome currently: https://apps.amandaghassaei.com/canvas-capture/demo/
