### ISSUE TITLE
Using canvas-capture without webpack ?

### ISSUE THREAD

**Issue by baylock** [amandaghassaei/canvas-capture#23]
Hi,
I'm trying to use canvas-capture for my own project (simple node server, no webpack and no module to import so far).
I installed canvas like this:
`npm install canvas-capture`
Then I go to my app.js file and add :
```
import { CanvasCapture } from 'canvas-capture';

CanvasCapture.init(
  document.querySelector('canvas'),
  { showRecDot: true }
);
etc..
```

I get the error message
`Uncaught TypeError: Failed to resolve module specifier "canvas-capture". Relative references must start with either "/", "./", or "../".`

So I try with this instead:
`import { CanvasCapture } from '../canvas-capture/dist/canvas-capture.js';`

And now I get:
`Uncaught SyntaxError: The requested module '../canvas-capture/dist/canvas-capture.js' does not provide an export named 'CanvasCapture'`

So when I go and check the canvas-capture.js file, on the first line code I see that it relies on webpack (that I don't use) and there is no function or class I can "export", as I'm asked the error message..
Many stuff is already using an "exports" instruction in this file but it's not the "export" expected.

So, is there a way to be able to get this to work (without using webpack) ?

I'm new to modules and bundlers, so getting my way through whatever webpack is doing in order to solve the problem is tricky for me.

Does this file pretty much implies that webpack HAS to be used to make it work and, if so, is there a way to work around that?

Three days I'm on this with no progress and I really need this, so I had to ask.

Thanks.

**Comment by amandaghassaei** [comment]
Sorry about the confusion, I've just added some additional docs about importing this library in a regular JS (not node) environment (e.g. by importing the file directly in your html document):

https://github.com/amandaghassaei/canvas-capture#installation

I've also added a simpler demo that does not use webpack or any compilation steps:
https://apps.amandaghassaei.com/canvas-capture/demo-simple/
the source code is here:
https://github.com/amandaghassaei/canvas-capture/tree/main/demo-simple

Does that solve your problem?  Please be sure to also download the latest version (I just updated it 5 min ago) bc I changed the name of the default export of the library (CanvasCaptureLib).

**Comment by baylock** [comment]
This is so nice of you. You took less than a few hours to address my issue and I'm grateful.

It didn't work at first because the "coi-serviceworker.min.js" caused an infinite loop when serving the files.
indeed, the doReload() inside that script was firing up repeatedly at launch.
What I did is get rid of the worker script completely and add this in my node server file instead:

```
 res.setHeader("Cross-Origin-Embedder-Policy", "require-corp");
 res.setHeader("Cross-Origin-Opener-Policy", "same-origin");
```
That solved the issue and that's one less javascript file to use, so that's cool.

And then, it seemed that canvas-capture didn't want to work with the PixiJS "ticker" (the exported video was  pitch black).
Using "requestAnimatedFrame" instead solved the problem.

And then, it worked. I could record an MP4 of my canvas, frame by frame! Thank you very much. It's awesome.

Still, at this point it is useless to me because after recording an MP4 (60fps, quality 1) for more than 35 frames (barely 600K), the video export is systematically aborted and I get this series of errors in the chrome console:

```
Pthread aborting at Error
    at n (blob:http://localhost:8080/d8664461-4705-4ed6-898e-87f480b305be:25:81)
    at ra (blob:http://localhost:8080/d8664461-4705-4ed6-898e-87f480b305be:199:201)
    at blob:http://localhost:8080/b53b5eae-22ea-4ae3-9422-8c9477d0e256:wasm-function[1996]:0x13dc78
    at blob:http://localhost:8080/b53b5eae-22ea-4ae3-9422-8c9477d0e256:wasm-function[341]:0x16b64
    at blob:http://localhost:8080/b53b5eae-22ea-4ae3-9422-8c9477d0e256:wasm-function[6232]:0x53788b
    at blob:http://localhost:8080/b53b5eae-22ea-4ae3-9422-8c9477d0e256:wasm-function[2595]:0x1d90bc
    at blob:http://localhost:8080/b53b5eae-22ea-4ae3-9422-8c9477d0e256:wasm-function[344]:0x17bce
    at blob:http://localhost:8080/b53b5eae-22ea-4ae3-9422-8c9477d0e256:wasm-function[2989]:0x248267
    at blob:http://localhost:8080/b53b5eae-22ea-4ae3-9422-8c9477d0e256:wasm-function[10506]:0x89de27
    at blob:http://localhost:8080/b53b5eae-22ea-4ae3-9422-8c9477d0e256:wasm-function[10169]:0x83f2e5
    
00M     d8664461-4705-4ed6-898e-87f480b305be:25 OOM
    n @ d8664461-4705-4ed6-898e-87f480b305be:25
    ra @ d8664461-4705-4ed6-898e-87f480b305be:199
    $func1996 @ b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x13dc78
    $Vd @ b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x16b64
    $func6232 @ b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x53788b
    $Zd @ b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x1d90bc
    $func344 @ b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x17bce
    $func2989 @ b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x248267
    $func10506 @ b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x89de27
    $func10169 @ b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x83f2e5
    $func3981 @ b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x341ad5
    $func6070 @ b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x513806
    $func2213 @ b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x1788d0
    $func6291 @ b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x53e21c
    $func3214 @ b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x27a8fc
    $func13041 @ b53b5eae-22ea-4ae3-9422-8c9477d0e256:0xad68fe
    $ae @ b53b5eae-22ea-4ae3-9422-8c9477d0e256:0xad7ba3
    f._main @ d8664461-4705-4ed6-898e-87f480b305be:217
    K @ d8664461-4705-4ed6-898e-87f480b305be:171
    $func12911 @ b53b5eae-22ea-4ae3-9422-8c9477d0e256:0xacb7da
    f.dynCall @ d8664461-4705-4ed6-898e-87f480b305be:28
    onmessage @ 27f9bce7-9e63-4c06-a8be-1fb65e73e7f6:1
    
worker.js     onmessage() captured an uncaught exception: RuntimeError: abort(OOM). 
    Build with -s ASSERTIONS=1 for more info.
    threadPrintErr | @ | 27f9bce7-9e63-4c06-a8be-1fb65e73e7f6:1
    -- | -- | --
    | onmessage | @ | 27f9bce7-9e63-4c06-a8be-1fb65e73e7f6:1

RuntimeError:     27f9bce7-9e63-4c06-a8be-1fb65e73e7f6:1 
    RuntimeError: abort(OOM). Build with -s ASSERTIONS=1 for more info.
    at n (d8664461-4705-4ed6-898e-87f480b305be:25)
    at ra (d8664461-4705-4ed6-898e-87f480b305be:199)
    at b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x13dc78
    at b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x16b64
    at b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x53788b
    at b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x1d90bc
    at b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x17bce
    at b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x248267
    at b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x89de27
    at b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x83f2e5

Uncaught RuntimeError: abort(OOM). Build with -s ASSERTIONS=1 for more info.
    at n (d8664461-4705-4ed6-898e-87f480b305be:25)
    at ra (d8664461-4705-4ed6-898e-87f480b305be:199)
    at b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x13dc78
    at b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x16b64
    at b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x53788b
    at b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x1d90bc
    at b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x17bce
    at b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x248267
    at b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x89de27
    at b53b5eae-22ea-4ae3-9422-8c9477d0e256:0x83f2e5
```

Is this something related to how your canvas-capture.js file is handling ffmpeg or is it something you can't do much about (issue on the ffmpeg side)?
EDIT: It seems to be related to the "ffmpeg-core.js" that is linked in line 26 of canvas-capture.js. At least, this is the file that throws the console "Pthread" error message for sure. Still, I don't know how to fix this yet.

Anyway, this is already a HUGE improvement thanks to you and I can't believe how fast you addressed my problem.
Thanks to you I'm 95% there already and I'm sure I'll find a way to cross that final obstacle.

Take care ! 

PS: feel free to close that issue and put it as solved. Unless you feel like there is something to be done about the PThread thing. But, a far as I'm concerned, you delivered 100%.

**Comment by amandaghassaei** [comment]
ok glad that you figured it out!  Yeah that error is way above my pay grade - something in ffmpeg.  For very large videos you might be better off saving as webm and then converting to mp4 using ffmpeg locally from the command line.  I do this whenever I need to download very large files and have found it to be much more reliable.  I wrote some notes on that in the readme "Converting WEBM to Other Formats": https://github.com/amandaghassaei/canvas-capture#converting-webm-to-other-formats

I wish this was all a lot easier, but I'm glad you were able to make it work.  I'm sure in the future this will be supported much better in the browser without all of the extra server headers etc.

closing this issue.

**Comment by baylock** [comment]
I thank you very much for all you did.
Your tool is amazing.
Yes, I’m trying to render a large canvas. I made it smaller since and it worked fine.

All the best.

Bachir Messaouri.
