### ISSUE TITLE
mp4 output quality

### ISSUE THREAD

**Issue by stijlfigurant** [amandaghassaei/canvas-capture#24]
Have set the settings to high, and/or bumped the ffmpeg settings to something similar or close to lossless (https://trac.ffmpeg.org/wiki/Encode/H.264#LosslessH.264), but keep getting washed out .mp4s as a result.

Could it be it is pre-encoding or something before punching it to ffmpeg?

https://github.com/amandaghassaei/canvas-capture/assets/402389/f4d959d6-2548-46d7-b726-0f9b06a8b556

Recorded pngs on the other hand are crisp 👌, so I might consider just piping those to ffmpeg..

PNG frame example
![frame_3](https://github.com/amandaghassaei/canvas-capture/assets/402389/d215fa37-a527-463f-a535-af94baa3a13b)

**Comment by amandaghassaei** [comment]
yes I've noticed this as well:
https://github.com/amandaghassaei/canvas-capture/issues/7

Let me know if you are able to get the results you are looking for via the png + ffmpeg (command line) route and what settings you used.   As I recall, I was having trouble getting even that to work, so I wasn't sure if it was an issue with my settings, ffmpeg, a limitation of mp4, or even just a limitation of the quicktime viewer that I'm using to watch the mp4s...

**Comment by stijlfigurant** [comment]
Certainly, there's two parts to this problem

**1 Getting PNGs to MP4**

Useful reference: https://hamelot.io/visualization/using-ffmpeg-to-convert-a-set-of-images-into-a-video/ 

FFMPEG/regex requires a leading 0s in the filename to make this work. In my test I added a single 0 on the frame names (frame_01.png), but that only scales to 99 images. It's probably useful to set that to like frame_0001.png.

**2 Colorspace compression with YUV240p**

Which is a little more complicated but applying some guidance from this reference got me to a more satisfying result https://trac.ffmpeg.org/wiki/colorspace. Anything but Yuv240p will get you issues in displaying it anywhere else than VLC I think.

Putting it together ```ffmpeg -r 30 -f image2 -pix_fmt rgba -s 1024x768 -i PNG_Frames_Capture/frame_%02d.png  -x264-params "keyint=15:no-deblock=1" -pix_fmt yuv420p -sws_flags spline+accurate_rnd+full_chroma_int -vf "colorspace=bt709:iall=bt601-6-625:fast=1" -color_range 1 -colorspace 1 -color_primaries 1 -color_trc 1 testcolorspace.mp4```

https://github.com/amandaghassaei/canvas-capture/assets/402389/f3da4b78-6447-4300-a53a-a39cc80572f6

**Comment by amandaghassaei** [comment]
going to close this as a duplicate, this will take more digging into ffmpeg or other encoder options to address.   will track this is feature requests as well: https://github.com/amandaghassaei/canvas-capture/discussions/29
