### ISSUE TITLE
best way to watermark a screenshot or video?

### ISSUE THREAD

**Issue by rishipandey125** [amandaghassaei/canvas-capture#28]
Hey! Amazing library! What would be the best way to watermark content via text or an image using this library? I am trying to watermark the actual canvas element which is proving to be very difficult, so I was curious if there was some way to watermark content on export. Thanks!

**Comment by amandaghassaei** [comment]
this library has no support for that, so the only way is to add the watermark to the WebGL canvas.  interesting feature request though, I'll think on that.

**Comment by amandaghassaei** [comment]
one thing to note is that the canvas can be saved by right clicking and save image as (try with the demo: https://apps.amandaghassaei.com/canvas-capture/demo/), so if you are not already applying a watermark to your canvas yourself, then the user still has the ability to save it out.  I think this feature would only be relevant to video/gif exports - though obviously the user can always screen record or access the canvas via the console.  There is no way to protect the images/animations completely unless you are applying the watermark in the original canvas rendering.

**Comment by amandaghassaei** [comment]
added to https://github.com/amandaghassaei/canvas-capture/discussions/29
going to close this for now.
