### ISSUE TITLE
Typo in demo

### ISSUE THREAD

**Issue by disambiguator** [amandaghassaei/canvas-capture#6]
The demo code references `onMP4ConversionProgress` which is seemingly gone from the API as well!

Thanks for the library, hope these little spots are helpful! :)

**Comment by amandaghassaei** [comment]
it is helpful, thanks!

hmm, I was confused by why typescript was even allowing this to happen and then found:
https://stackoverflow.com/questions/59086524/typescript-function-accepting-incorrect-argument-with-no-error

fixed by: https://github.com/amandaghassaei/canvas-capture/commit/8396c3ae5aba1d44af34b75366062abbd671c9c9

**Comment by disambiguator** [comment]
Ah yup! I have TS strict mode on for my project, so it caught this immediately. Woo!

**Comment by amandaghassaei** [comment]
I don't think it's strict mode issue though (I have `strict: true` in my tsconfig).  It's whether you do:

```
const MP4_OPTIONS = {
	name: 'demo-mp4',
	format: CanvasCapture.MP4,
	quality: 1,
	fps: 60,
        randomKey: true,
	onExportProgress: (progress: number) => console.log(`MP4 export progress: ${progress}.`),
	onExportFinish: () => console.log(`Finished MP4 export.`),
};
CanvasCapture.bindKeyToVideoRecord('v', MP4_OPTIONS);

(no ts error)
```

versus:
```
CanvasCapture.bindKeyToVideoRecord('v', {
	name: 'demo-mp4',
	format: CanvasCapture.MP4,
	quality: 1,
	fps: 60,
        randomKey: true,
	onExportProgress: (progress: number) => console.log(`MP4 export progress: ${progress}.`),
	onExportFinish: () => console.log(`Finished MP4 export.`),
});

(ts error)
```

apparently that's how ts is "supposed" to work :/

**Comment by disambiguator** [comment]
Ah, you're so right. Exact vs. inexact types, since it still fulfills the interface it's fine.

I guess if you _really_ cared, you could export `MP4_OPTIONS` from your type declarations and do 
`const MP4_OPTIONS: MP4_OPTIONS = ...`

but 🤷🏽 whatever.
