### ISSUE TITLE
Unlock all features of CCapture

### ISSUE THREAD

**Issue by mishagrin** [amandaghassaei/canvas-capture#9]
Hello!

CCapture alters requestAnimationFrame method, if i remember correctly, and because of that i could render video with constant framerate. Canvas animation slows down, and CCapture capture each frame very slowly.

Is it possible to do same thing with canvas-capture?

**Comment by mishagrin** [comment]
@amandaghassaei 
You're right!

I get how to make it work

Thanks!

**Comment by mishagrin** [comment]
@amandaghassaei 
Are you planning to implement `timeLimit` option from CCapture?

Also if you could bind callback to each 'capture tick', that would be awesome. So i could update animation, for example, on each captured frame.

I can't figure out how to render animation with specific duration. Vanilla approach with `setTimeout` gives different results based on machine specs

**Comment by amandaghassaei** [comment]
closing this one.
